### ISSUE TITLE
Opening table produces error on client.

### ISSUE THREAD

**Issue by KJP12** [QPCrummer/FabricAutoCrafter#1]
## Summary
Opening the autocrafting table produces an error on the client regardless of if the client has the mod installed. The server doesn't produce the log at all and is unaware of any errors.

Suspecting that the create & overwrite tactic causes issues on the client due to getting a smaller inventory than expected. The real source and a potential fix does seem like it might be a while to figure out.

## Steps to Reproduce
1. Place the autocrafting table
2. Open it.

## Logs
<details><summary>The logs</summary>

```
[22:47:12] [Render thread/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 46 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7611(class_1703.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7610(class_1703.java:583) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11153(class_634.java:1051) ~[client-intermediary.jar:?]
	at net.minecraft.class_2649.method_11439(class_2649.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_2649.method_11054(class_2649.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$zci000$redirectExecuteTask(class_1255.java:521) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
</details>

**Comment by QPCrummer** [comment]
I can also replicate this issue on the original autocrafting mod
