### ISSUE TITLE
crash with libjf on launch

### ISSUE THREAD

**Issue by DadoIrie** [QPCrummer/FabricAutoCrafter#9]
https://mclo.gs/UTQZADB here's the complete log - the modpack has grown quite a bit, but the conflict here is clear
posting this just in case if autocrafter could do something which fixes it - it might be also only a client related issue here, but can't tell for sure 

```
 Could not apply patch: class io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch on com.github.tatercertified.fabricautocrafter.AutoCrafter
java.lang.RuntimeException: Could not load super class eu/pb4/polymer/core/api/block/PolymerBlock of com/github/tatercertified/fabricautocrafter/AutoCrafter
	at io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch.scanInterfaces(InterfaceImplTargetPatch.java:42) ~[libjf-unsafe-v0-3.12.5-144477310d0fb52f.jar:?]
	at io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch.apply(InterfaceImplTargetPatch.java:23) ~[libjf-unsafe-v0-3.12.5-144477310d0fb52f.jar:?]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:91) ~[libjf-unsafe-v0-3.12.5-144477310d0fb52f.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.22.jar:?]
	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:73) ~[supermartijn642corelib-1.1.14-fabric-mc1.20.1.jar:?]
	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:69) ~[supermartijn642corelib-1.1.14-fabric-mc1.20.1.jar:?]
	at net.minecraft.class_310.handler$mdc000$supermartijn642corelib$beforeInit(class_310.java:55524) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: eu.pb4.polymer.core.api.block.PolymerBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch.scanInterfaces(InterfaceImplTargetPatch.java:40) ~[libjf-unsafe-v0-3.12.5-144477310d0fb52f.jar:?]
	... 23 more
```

**Comment by DadoIrie** [comment]
https://mclo.gs/6Qu0aLj
well, does happen also with libjf - don't really have time now investigating this any further - will see if getting some time for that

**Comment by QPCrummer** [comment]
It seems to me that this is an issue relating to a dependency we use, Polymer. A cool thing Fabric allows is overriding dependencies of mods with newer versions. Could you try sticking this newer version of Polymer into your mods folder and seeing if it fixes the issue? https://modrinth.com/mod/polymer/version/0.5.15+1.20.1

**Comment by DadoIrie** [comment]
yeah - using a updated version of polymer resolve it - closing issue - thanks
